---
-
  get_url:
    dest: /home/{{user_name | quote }}
    group: "{{user_name | quote }}"
    mode: 493
    owner: "{{user_name | quote }}"
    url: "{{replication_url}}"
  name: "Download replica script using get_url"
-
  name: "Run a replica script with arguments (using 'cmd' parameter)"
  shell: /home/{{user_name | quote }}/{{replication_name}} {{domain_name | quote }}
  args:
    executable: /bin/bash
