dist: trusty

language: python

node_js: "0.12"

python: "3.5"

addons:
  apt:
    sources:
    - sourceline: 'deb https://packages.microsoft.com/repos/azure-cli/ trusty main'
      key_url: 'https://packages.microsoft.com/keys/microsoft.asc'
    packages:
      - azure-cli # Install the Azure CLI tools

cache:
  - directories: node_modules
  - pip

env:
  - PYTHONUNBUFFERED=TRUE

install:
  - npm install # Install task runners for lint checking.
  - pip install azure keyring pycurl # Install Azure Python SDK

before_script:
  - ssh-keygen -q -f azure_moodle_id_rsa -N "" # Generate SSH keys to send to deployment

script:
  - npm test
  - ./etc/travis.py

after_script: # Teardown group and created resource after build.
  - test -n "$SPNAME" -a -n "$SPPASSWORD" -a -n "$SPTENANT" && az login --service-principal -u "$SPNAME" -p "$SPPASSWORD" --tenant "$SPTENANT" && az group delete -g azmdl-travis-$TRAVIS_BUILD_NUMBER -y --no-wait

notifications:

webhooks: https://outlook.office.com/webhook/e75ee820-3466-49a6-bb0f-ecae0daf8fe1@72f988bf-86f1-41af-91ab-2d7cd011db47/TravisCI/00abc9d7ce1044818f216da49d30d54d/a38fc8f6-fb60-4169-bde6-dd2bbf01304f
