dist: trusty
sudo: off

branches:
  only:
  - master

language: node_js # Base language is Nodejs (used for liniting and basic validation).

addons:
  apt:
    sources:
    - sourceline: 'deb https://packages.microsoft.com/repos/azure-cli/ trusty main'
      key_url: 'https://packages.microsoft.com/keys/microsoft.asc'
    packages:
      - azure-cli # Install the Azure CLI tools

before_script:
  - npm install -g grunt-cli # Install task runners for lint checking.

node_js:
  - "0.12"

cache:
  directories:
    - node_modules

script: # Run the lint tests, then if env vars are present validate the template then try building the stack.
  - npm test
  - if [ "$SPNAME" != ""  -a  "$SPPASSWORD" != ""  -a  "$SPTENANT" != ""  -a  "$SPSSHKEY" != "" ]; then
      export RUNBUILD="true"
      export AZMDLGROUP="azmdl-travis-$TRAVIS_BUILD_NUMBER"
    fi
  - if [ -z "$LOCATION" ]; then
      export LOCATION="westus"
    fi
  - if [ "$RUNBUILD" = "true" ]; then
      echo "Running Azure setup steps."
      az login --service-principal -u "$SPNAME" -p "$SPPASSWORD" --tenant "$SPTENANT"
      az group create -l "$LOCATION" -g "$AZMDLGROUP"
    else
      echo "Skipping Azure setup."
    fi
  - if [ "$RUNBUILD" = "true" ]; then
      echo "Running Azure validation step."
      VALIDATION_RESULT=$(az group deployment validate --resource-group "$AZMDLGROUP" --template-file azuredeploy.json --parameters azuredeploy.parameters.json --parameters sshPublicKey="$SPSSHKEY")
      if [ -n "$VALIDATION_RESULT" ]; then
        echo "Azure template validation failed! Error message:"
        echo $VALIDATION_RESULT
        exit 1
      fi
    else
      echo "Skipping Azure validation."
    fi
  - if [ "$RUNBUILD" = "true" ]; then
      echo "Running Azure build step."
      az group deployment create --resource-group "$AZMDLGROUP" --template-file azuredeploy.json --parameters azuredeploy.parameters.json --parameters sshPublicKey="$SPSSHKEY" --debug --verbose
    else
      echo "Skipping Azure build."
    fi

after_script: # Teardown group and created resource after build.
  - if [ "$RUNBUILD" = "true" ]; then
      az group delete -g "moodle-azure-$TRAVIS_BUILD_NUMBER" -y --no-wait
    fi
