language: node_js

before_script:
  - npm install -g grunt-cli mocha

node_js:
  - "0.12"

env: VALIDATION_HOST=http://template-bot-a-central.centralus.cloudapp.azure.com:3000

cache:
  directories:
    - node_modules
