dist: trusty
sudo: off

language: node_js # Base language is Nodejs (used for liniting and basic validation).

addons:
  apt:
    sources:
    - sourceline: 'deb https://packages.microsoft.com/repos/azure-cli/ trusty main'
      key_url: 'https://packages.microsoft.com/keys/microsoft.asc'
    packages:
      - azure-cli # Install the Azure CLI tools

before_script:
  - npm install -g grunt-cli mocha # Install task runners for lint checking.

node_js:
  - "0.12"

cache:
  directories:
    - node_modules

# Node JS environments in Travis run `npm test` by default as the entry point
# By default `npm test` invokes the "scripts"->"test" section of package JSON

script:
  - az