dist: trusty
sudo: off

language: node_js # Base language is Nodejs (used for liniting and basic validation).

addons:
  apt:
    sources:
    - sourceline: 'deb https://packages.microsoft.com/repos/azure-cli/ trusty main'
      key_url: 'https://packages.microsoft.com/keys/microsoft.asc'
    packages:
      - azure-cli # Install the Azure CLI tools

before_script:
  - npm install -g grunt-cli # Install task runners for lint checking.

node_js:
  - "0.12"

cache:
  directories:
    - node_modules

script: # Run the lint tests, then if env vars are present validate the template then try building the stack.
  - npm test
  - if [ $SPNAME ] && [ $SPPASSWORD ] && [ $SPTENANT ]; then
      echo "Runnig Azure validation and build steps.";
      az login --service-principal -u "$SPNAME" -p "$SPPASSWORD" --tenant "$SPTENANT";
      az group create -l westus -g "moodle-azure-$TRAVIS_BUILD_NUMBER";
      az group deployment validate --resource-group "moodle-azure-$TRAVIS_BUILD_NUMBER" --template-file azuredeploy.json --parameters azuredeploy.parameters.json --debug;
      az group deployment create --resource-group "moodle-azure-$TRAVIS_BUILD_NUMBER" --template-file azuredeploy.json --parameters azuredeploy.parameters.json --debug;
    else
      echo "Skipping Azure validation and build.";
    fi

after_script: # Teardown group and created resource after build.
  - if [ $SPNAME ] && [ $SPPASSWORD ] && [ $SPTENANT ]; then
      az group delete -g "moodle-azure-$TRAVIS_BUILD_NUMBER" -y;
    fi